### ISSUE TITLE
Viewer doesn't load in IE

### ISSUE THREAD

**Issue by cmoore01** [JamesAPetts/ohif-viewer-XNAT-plugin#10]
If you attempt to load the viewer in IE11 by clicking the "View Session" link, nothing appears to happen in the UI. Backing up, I notice this in the IE dev console when reloading the page
<img width="291" alt="screen shot 2019-01-08 at 1 30 56 pm" src="https://user-images.githubusercontent.com/7414724/50854129-d9da1800-1349-11e9-9770-500385e339d7.png">

Following the link takes me to:
<img width="707" alt="screen shot 2019-01-08 at 1 31 05 pm" src="https://user-images.githubusercontent.com/7414724/50854158-efe7d880-1349-11e9-8458-99d25da124f9.png">
That is defined on line 31 of https://github.com/JamesAPetts/ohif-viewer-XNAT-plugin/blob/xnatRoi-beta-1.8/src/main/resources/META-INF/resources/templates/screens/xnat_imageSessionData/actionsBox/ViewInOHIFViewer.vm . Note that if the issue is IE not supporting backticked quotes (with `), there are several more instances of it in this file alone.

**Comment by JamesAPetts** [comment]
Hey @cmoore01 , ahh this is interesting. The viewer itself is bundled to function in IE11, but i'd never tested the XNAT interface in IE11. It seems turbine does no kind of bundling/transpiling, and the code given just works as is. I'll just have to manually convert the vm templates from ES6 to ES5.

**Comment by JamesAPetts** [comment]
Also I've been talking to Erik Ziegler, and IE11 is still on the roadmap for OHIF right now, but richer functionality might require this to be deprecated at some point in the future. We can discuss this on slack.

**Comment by JamesAPetts** [comment]
Transpilled down to ES5, confirmed still working in evergreen browsers, will check IE when I'm home.

**Comment by cmoore01** [comment]
Now I can get the modal containing the viewer to launch, but it's just an empty black box. 
<img width="1326" alt="screen shot 2019-01-14 at 10 44 07 am" src="https://user-images.githubusercontent.com/7414724/51126679-586f0380-17e9-11e9-874c-663e34f8ddea.png">

The IE console complains about a syntax error in a minified JS file:
<img width="505" alt="screen shot 2019-01-14 at 10 43 05 am" src="https://user-images.githubusercontent.com/7414724/51126714-6ae93d00-17e9-11e9-87db-d68adfa34d41.png">

**Comment by JamesAPetts** [comment]
As far as I'm concerned for now, we've mostly fixed the IE 11 issues. We'll try to push for more native IE11 support in the future. The only issue left is the rendering of some SVG's, but the viewer is at least usable for now.

**Comment by JamesAPetts** [comment]
I'm going to close this for now to clean up the board a bit. We can reopen it in the future.
