### ISSUE TITLE
Viewer doesn't load for users without write access

### ISSUE THREAD

**Issue by cmoore01** [JamesAPetts/ohif-viewer-XNAT-plugin#11]
To recreate:
1. Login as a collaborator of a project with at least one session for which the JSON has not been generated.
2. Load the session which hasn't had the JSON generated.
3. Click the "View Session" link.

You get the alert about generating the metadata, but the REST calls fail since the user doesn't have write access. Presumably there should either be some messaging saying that you need at least member-level access, but that would be pretty strange to end-users, because from their perspective, they shouldn't need write access to just view the data.

Also, note that the "View Session" link doesn't even show up **at all** for the guest user.

**Comment by JamesAPetts** [comment]
This is strange, I had worked out this stuff for 1.7.4.1. I'll have a look into to see if anything has changed.

**Comment by JamesAPetts** [comment]
Aha, sorry didn't read this correctly earlier, been a hectic morning. This can be fixed, along with #9 by fixing the automation which seems to have broken recently.

**Comment by JamesAPetts** [comment]
This will be fixed with #9, as the JSONification should be automatic. Closing this for now unless you have further issues.
