### ISSUE TITLE
Attempting to retrieve DICOM data file-by-file doesn't scale

### ISSUE THREAD

**Issue by cmoore01** [JamesAPetts/ohif-viewer-XNAT-plugin#13]
The viewer seems to request each individual DICOM file as far as I can tell. This causes it to not work (without waiting enormous amounts of time) for series with a large file count. Additionally, it will be making thousands, or even tens of thousands of file requests to the server, which will probably cause performance issues.

I made a 35062 instance-count series for a completely different reason, which you can find here, if you want to play with it: ftp://ftp.nrg.wustl.edu/pub/data/big.zip. Note that the pixel data is basically static, and it's the same in each "instance" (basically just copied with some modifications like Instance Number and SOP Instance UID).

Note: this is not much of an edge case at all. We're getting increasing amounts of data on CNDA with instance counts even **larger** than this (~80K files in one series).

**Comment by JamesAPetts** [comment]
I'm well aware of this issue, and its certainly something we need to address. Its been on the back burner for a while as I was waiting for the table view plugin to go core, which I originally heard was going in 1.7.5 back last year. I think it'd make sense to make a small JSON per scan, which can be aggregate into a request client side at run time.

Other than that I'm not sure how to avoid lots of requests, the images need to be grabbed and parsed, perhaps we can discuss possible solutions in slack.

**Comment by JamesAPetts** [comment]
As this repo is being deprecated and moved to Bitbucket, I'm closing this issue, feel free to bring it back up in the XNAT Development slack.
