### ISSUE TITLE
Wrong field pulled for "Study Date"

### ISSUE THREAD

**Issue by cmoore01** [JamesAPetts/ohif-viewer-XNAT-plugin#14]
When clicking the "Measurements" button, the date being displayed is today's date. Presumably, that's because I uploaded that session today. However, that's not the "Study Date", which is a much older date in the DICOM header (0008,0020). Technically, it's also in the session object usually, but just like issue #12, it can't be safely assumed to always be there.

<img width="1269" alt="screen shot 2019-01-09 at 2 08 38 pm" src="https://user-images.githubusercontent.com/7414724/50925746-da8daf80-1418-11e9-9cb9-446418a85e52.png">

**Comment by JamesAPetts** [comment]
Hey @cmoore01 , the measurement tab is something that's recently been pulled in from the core OHIF viewer, it seems a bit incomplete, so I'll remove it until/if we have a proper use case for it. Right now the ROIs and Masks measurements have their own menus which I created before the inception of the measurement interface. Either way I'll check into this and push the info to the core team.

**Comment by JamesAPetts** [comment]
Removed this incomplete interface for now, it may return in the future!
