### ISSUE TITLE
"OHIF XNAT" link goes to incomplete URL for sites with non-ROOT app context

### ISSUE THREAD

**Issue by cmoore01** [JamesAPetts/ohif-viewer-XNAT-plugin#15]
Very minor, reported for completeness' sake.

Some XNAT installations use a non-ROOT app context (meaning, the XNAT is accessible at a URL like "http://10.1.100.17/xnat" instead of "http://10.1.100.17"). In this scenario, when clicking on the little XNAT logo or "OHIF Viewer XNAT..." text in the top left of the viewer, the user is sent to the URL without the app context (e.g. "http://10.1.100.17" instead of "http://10.1.100.17/xnat"), resulting in a 404.

**Comment by JamesAPetts** [comment]
Hey @cmoore01, in general I've configured the plugin to function well in a non-root context, as I use this myself.

What you've stumbled upon here seems a relic from the "vanilla" viewer. I'll just remove that hyper-link completely, as it serves no purpose, thanks for the catch!

**Comment by JamesAPetts** [comment]
Fixed on 1.8 beta branch.
