### ISSUE TITLE
SOP Class lists are missing entries, and incorrect in some cases

### ISSUE THREAD

**Issue by cmoore01** [JamesAPetts/ohif-viewer-XNAT-plugin#16]
https://github.com/JamesAPetts/ohif-viewer-XNAT-plugin/blob/151dd2bdf7696a46b97d56117fa7e7bd4223d74a/src/main/java/org/nrg/xnatx/ohifviewer/inputcreator/CreateOhifViewerMetadata.java#L141-L155

These lines sort the instances. However, if an instance isn't in either the single-frame or the multi-frame list, the instance is ignored. This issue is exacerbated by the incompleteness and inaccuracies in the lists. For example, you can get an example of a SOP instance with the _LegacyConvertedEnhancedCTImageStorage_ SOP class here: ftp://medical.nema.org/medical/dicom/DataSets/WG30/Frederick/PETCT/OneMouseDynamicFDGPET_20150512/Converted/DICOM/testtoenhanceddynamicct.dcm . In general, I've been really impressed with how this viewer can display a bunch of the test data I use that neither XNAT's native snapshot generation nor the XTK-based image viewer that ships with XNAT can display at all. In this case, though, the viewer doesn't even try to display it, because it can't recognize the SOP class, but XNAT can display snapshots just fine:
![xnat_e00009_0_qc](https://user-images.githubusercontent.com/7414724/50934663-eab08980-142e-11e9-86b3-7b6826e6a128.gif)
I can provide some examples of other missing SOP classes too if you would like.

As for the list themselves, the "NM Image Storage" SOP class supports multi-frame images: http://dicom.nema.org/medical/dicom/current/output/chtml/part03/sect_A.5.4.html . It's sufficient to see that "Multi-frame" module for the SOP class. However, it's not necessary that the "Multi-frame" module be included. The "Enhanced MR Image Storage" SOP class is also used for multi-frame images, but it doesn't use that module: http://dicom.nema.org/medical/dicom/current/output/chtml/part03/sect_A.36.2.3.html . Both of these SOP classes are currently included in the SopClassLists.SINGLE_FRAME_SOP_CLASS_UIDS list, and there are other similar cases that I haven't gone through.

**Comment by JamesAPetts** [comment]
Hey @cmoore01 , thanks for this. The list I generated was mainly based on what we had encountered as data we internally would like to display, and anything from [this list](https://www.dicomlibrary.com/dicom/sop/) that appears to be imaging data. The list is not exhaustive, and it appears there are types I've missed as you point out. Its very much been a case of making sure new data works as we encounter it, we can discuss this on Slack and iterate!

**Comment by cmoore01** [comment]
In particular, Dan mentioned that viewing mammography and tomosynthesis (tomography?) were important. I tried out viewing data from 3 particular SOP classes:

`
1.2.840.10008.5.1.4.1.1.1.2 : Digital Mammography X-Ray Image Storage - For Presentation
1.2.840.10008.5.1.4.1.1.1.2.1 : Digital Mammography X-Ray Image Storage - For Processing
1.2.840.10008.5.1.4.1.1.13.1.3 : Breast Tomosynthesis Image Storage
`

Only the first SOP class was able to be displayed in the viewer. I think it's fine (actually, *correct*) that the "For Processing" images aren't viewable, but the tomo images probably should be viewable.

**Comment by JamesAPetts** [comment]
I've refactored the list into one, since I can just use the `dicomweb` image loader of `cornerstoneWADOImageLoader` for every modality it seems (I was already loading multiframe images under e.g. `Enhanced MR Image Storage` even though this was listed under "singleframe".

The list should more comprehensively include all image modalities.

**Comment by JamesAPetts** [comment]
As this repo is being deprecated and moved to Bitbucket, I'm closing this issue, feel free to bring it back up in the XNAT Development slack.
