### ISSUE TITLE
Viewer not available to guest user

### ISSUE THREAD

**Issue by cmoore01** [JamesAPetts/ohif-viewer-XNAT-plugin#19]
I mentioned this in passing in #11, but it should really just be its own issue. When XNAT does not require login (Administer > Site Administration > Security > Require User Login), and a user who is not authenticated (and therefore viewing XNAT as the "guest" account) is viewing data in a *public* project, there is no "View Session" available.
<img width="1148" alt="screen shot 2019-01-14 at 2 25 25 pm" src="https://user-images.githubusercontent.com/7414724/51138985-48b2e780-1808-11e9-8a31-c40e1cdbb32c.png">

**Comment by JamesAPetts** [comment]
Fixed. Thanks!
