### ISSUE TITLE
Improve messaging when no series are compatible with the viewer

### ISSUE THREAD

**Issue by cmoore01** [JamesAPetts/ohif-viewer-XNAT-plugin#21]
<img width="1060" alt="screen shot 2019-01-14 at 3 20 44 pm" src="https://user-images.githubusercontent.com/7414724/51141873-ffff2c80-180f-11e9-9cb6-d18d70dd7a96.png">

There are many scenarios where this could arise:
1. Session has no scans, because they're going to be added later.
2. Session has several scans, but none of them are compatible with the viewer (perhaps unsupported SOP classes).
3. Session only has Nifti scans (not supported yet).

In these cases, it would be nice for the message displayed to say something like "No scans can be displayed in this study" (whatever sounds good to you). The issue with the current phrasing (I assume it's what the cornerstone viewer wants to do by default) is that a user will think "OK, so I just drag my scan into this to get it to display...wait where are the scans? How does this work?"

**Comment by JamesAPetts** [comment]
Good catch, I guess I can just check the JSON before loading the viewer and pop up a warning instead of opening the viewer.

**Comment by JamesAPetts** [comment]
This is fixed. Small UI question in Slack.
