### ISSUE TITLE
Long values for Series Number are often truncated

### ISSUE THREAD

**Issue by cmoore01** [JamesAPetts/ohif-viewer-XNAT-plugin#23]
<img width="277" alt="screen shot 2019-01-15 at 9 43 05 am" src="https://user-images.githubusercontent.com/7414724/51197011-01833000-18b6-11e9-919b-08c082258b41.png">

**Note 1:** This issue is highly related to #22 

**Note 2:** The DICOM element `Series Number (0020,0011)` has a VR of `IS`. I don't see anything in the _General Series Module_ that would place any restriction on the value other than what's enforced by the VR, but I don't think I've ever seen a **negative integer** series number (that sounds really weird). So, the largest number I would expect to see in practice would be `2^{31} - 1 = 2147483647`. That's a 10 digit number.
<img width="738" alt="screen shot 2019-01-15 at 11 12 46 am" src="https://user-images.githubusercontent.com/7414724/51197497-570c0c80-18b7-11e9-8e07-cef2178798c3.png">

From Note 2, I've listed my thoughts as to why 10 digits would be the largest value you would likely find in this field (even allowing a negative value just bumps it to 11). As such, it's probably best to not truncate this field at all, right? In the particular session where I took the screenshot at the top, there were two scans with series numbers **2429000** and **2429001**. Since it was truncated after 3 digits, you wouldn't have been able to tell them apart in the series list (technically only one showed up in the list since the other had an unrecognized SOP class, but that's not super relevant).

**Comment by JamesAPetts** [comment]
see #22 .
