### ISSUE TITLE
Series list should have a scroll bar

### ISSUE THREAD

**Issue by cmoore01** [JamesAPetts/ohif-viewer-XNAT-plugin#24]
The top answer on https://ux.stackexchange.com/questions/58087/is-it-safe-to-assume-everyone-uses-has-mouse-wheels lists some very solid reasons why not to hide scroll bars. The series list in the viewer can be scrolled with the mouse scroll wheel. That's definitely a good thing, but for people without a scroll wheel, or who don't know how to use it, etc., there doesn't seem to be another way (like a standard scroll bar) to navigate the series list.

**Comment by JamesAPetts** [comment]
See #22 .

**Comment by JamesAPetts** [comment]
Coming in next patch:

![Screen Shot 2019-04-15 at 10 03 20](https://user-images.githubusercontent.com/25818497/56120309-c8666480-5f65-11e9-8ae7-cb0314d2e88b.png)

I've got a similar styled scrollbar for the XNAT navigation on the right side.
