### ISSUE TITLE
Switching between views of series causes crash from memory leak

### ISSUE THREAD

**Issue by cmoore01** [JamesAPetts/ohif-viewer-XNAT-plugin#25]
[mem_leak.zip](https://github.com/JamesAPetts/ohif-viewer-XNAT-plugin/files/2774273/mem_leak.zip)

Unfortunately, I'm not quite sure how to describe the action I keep repeating, so I've attached a video. If I don't have the dev tools open, switching between this single view and dual-view crashes the browser from a memory exception. In the Activity Monitor for my computer, I've seen an instance of `Google Chrome Helper` go as high as `8.5 GB` before crashing.

Note also that you can see the performance degrade fairly significantly before the crash occurs.

**Comment by JamesAPetts** [comment]
Hey @cmoore01 , I've confirmed this is an issue in the core OHIF-Viewer. Not sure when It crept in, I'll cross post it there.

**Comment by JamesAPetts** [comment]
The fix has been propagated through to the beta-1.8 fork now. All good for me in FF/Chrome/Safari. Let me know if you have any other issues.
