### ISSUE TITLE
Plugin installation for docker

### ISSUE THREAD

**Issue by jonasscherer** [JamesAPetts/ohif-viewer-XNAT-plugin#3]
Hey,
is it possible to install plugins with an docker deployment?
I tried to move the jar file to **/data/xnat/home/plugins**, but xnat doesn't seem to install it.
thx

**Comment by JamesAPetts** [comment]
Hey @jonasscherer,
I haven't used Docker deployment myself, but I'm sure this is possible as the XNAT team have trialed this plugin on dockerized XNAT. I would direct you to post this question in the google group, where I'm sure you'll get a useful response: https://groups.google.com/forum/#!forum/xnat_discussion.
