### ISSUE TITLE
Study fails to load in shared project context

### ISSUE THREAD

**Issue by cmoore01** [JamesAPetts/ohif-viewer-XNAT-plugin#8]
Version: BETA-1.8.0-SNAPSHOT (https://github.com/JamesAPetts/ohif-viewer-XNAT-plugin/blob/xnatRoi-beta-1.8/dist/ohif-viewer-BETA-1.8.0-SNAPSHOT.jar?raw=true)

Steps to recreate:
1. Create two new projects, "A" and "B".
2. Upload a session to A.
3. Share the session from A into B.
4. Load the session in the context of project B. This can be done by going to the project page for B, clicking on the link for the subject in the Subjects tab, and then clicking on the link to the session.
<img width="1151" alt="screen shot 2019-01-08 at 10 54 01 am" src="https://user-images.githubusercontent.com/7414724/50849176-d475d100-133b-11e9-8986-de8d920662b3.png">
5. Click the "View Session" link

Note that the two calls to the plugin fail:
<img width="600" alt="screen shot 2019-01-08 at 10 54 59 am" src="https://user-images.githubusercontent.com/7414724/50849208-ec4d5500-133b-11e9-9a0a-01ffd7880f90.png">
<img width="543" alt="screen shot 2019-01-08 at 10 55 09 am" src="https://user-images.githubusercontent.com/7414724/50849213-efe0dc00-133b-11e9-8de1-3fe466f2408a.png">

**Comment by JamesAPetts** [comment]
Thanks for the detailed reproduction of this, I'll give it a look.

**Comment by JamesAPetts** [comment]
Shared session and shared subject views came in around 1.12 and 1.15 respectively.
