### ISSUE TITLE
Study JSON becomes out of date when session is updated

### ISSUE THREAD

**Issue by cmoore01** [JamesAPetts/ohif-viewer-XNAT-plugin#9]
This is just one of many, many, many ways that a session in XNAT (or a scan, or scan resource) can change such that the cached JSON is no longer valid.

1. Load the viewer for a session.
2. Close the viewer.
3. Delete one of the scans on the session.
4. Open the viewer again.
<img width="1977" alt="screen shot 2019-01-08 at 12 52 31 pm" src="https://user-images.githubusercontent.com/7414724/50852281-b8c2f880-1344-11e9-892b-cafeee8bbce3.png">

Note that attempting to generate the session JSON again returns a 201 status code, and the problematic behavior persists. The ways that come to mind on how to address this would be:
1. When a change occurs that requires regeneration of the session JSON, this will be detected and done automatically, either when the change is triggered, or when the session is next attempted to be viewed. This is the "optimal" solution in some sense because it requires no action from either an admin or a user, but it's unfortunately likely **very difficult**. The set of actions that would require regeneration of the JSON would include, but not be limited to:
- Update of the session metadata (label changed, etc.)
- Reassigning of the session to a new subject, or changing the subject label (the subject label is hardcoded into the "url" property of your "instance" objects)
- Moving the session to a new project (see previous point)
- Deletion of a scan
- Addition of a scan
- Addition of scan resource
- Deletion of scan resource
- Modification of a scan resource
Even **if** all of these actions are recorded with a time, they definitely won't be all in the same spot, because some deal with the session, and some deal with child scans, and even child scan resources.
2. Allow the REST call to regenerate the session JSON, and provide a button to trigger it. This sounds a bit ugly for an end-user to be forced to do, but it's also probably orders of magnitude easier to implement.

**Comment by JamesAPetts** [comment]
Thanks @kelseym!

**Comment by cmoore01** [comment]
This makes the behavior better, but it doesn't address all cases. For example, the steps listed at the beginning of this bug still cause the same error.

**Comment by cmoore01** [comment]
When deleting the scan via the selectable table, the scan gets removed from what the viewer tries to load *if and only if* the "remove files" checkbox remains *unchecked*. I have no explanation for why that would be the case, that's just what I've observed.
<img width="479" alt="screen shot 2019-01-14 at 1 30 13 pm" src="https://user-images.githubusercontent.com/7414724/51135853-a0e5eb80-1800-11e9-93fe-9dc33369924f.png">

**Comment by JamesAPetts** [comment]
> This makes the behavior better, but it doesn't address all cases. For example, the steps listed at the beginning of this bug still cause the same error.

This should only occur once if done rapidly, as deleting the scan will cause a rebuild of the JSON.

> When deleting the scan via the selectable table, the scan gets removed from what the viewer tries to load if and only if the "remove files" checkbox remains unchecked. I have no explanation for why that would be the case, that's just what I've observed.

Hmm, this is indeed odd. Could this be a core issue, why would the automation script depend on whether the files are deleted from the disk or not? Surely the `Removed scan` event should still trigger?

**Comment by JamesAPetts** [comment]
As this repo is being deprecated and moved to Bitbucket, I'm closing this issue, feel free to bring it back up in the XNAT Development slack.
